version: "3.9"
services:
  api:
    build: ./services/backend
    ports:
      - 4000:4000
    environment:
      - DENO_INSTALL=/root/.deno
      - PATH=$DENO_INSTALL/bin:$PATH
  db:
    build: ./services/database
    volumes:
      - ./services/database/db/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=muhammad
      - POSTGRES_PASSWORD=math
      - POSTGRES_DB=app
    ports:
      - 5432:5432
